
language: cpp

os: linux

compiler:
  -gcc
  -clang

aaddons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_install:
  - chmod u+x travis_setup.sh
  - source ./travis_setup.sh

install:
  - $CC --version
  - $CXX --version


script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .. --target detector_unit_test
  - sudo ./detector_unit_test
