
language: cpp

os: linux

compiler:
  -gcc
  -clang

addons:
  apt:
    sources:
      - george-edison55-precise-backports # cmake 3.2.3 / doxygen 1.8.3
    packages:
      - cmake
      - cmake-data

before_install:
  - sudo add-apt-repository -y ppa:george-edison55/precise-backports
  - sudo apt-get update -y
  - chmod u+x travis_setup.sh
  - source ./travis_setup.sh
  - git clone --recursive https://github.com/boostorg/boost.git
  - cd boost
  - sudo ./bootstrap.sh --with-libraries="program_options"
  - sudo ./b2 install

install:
  - $CC --version
  - $CXX --version
  - sudo apt-get install cmake cmake-data -y

script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build . --target detector_unit_test
  - sudo ./detector_unit_test
