
language: cpp

os: linux

compiler:
  -gcc
  -clang

before_install:
  - chmod u+x travis_setup.sh
  - source ./travis_setup.sh

install:
  - $CC --version
  - $CXX --version


script:
  - make
  - make unit_test
  - sudo ./unit_test


