
language: cpp

os: linux

compiler:
  -gcc
  -clang

adons:
    apt:
        packages:
            - cmake


before_install:
  - sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
  - sudo apt-get update -qq
  - sudo apt-get install cmake
  - chmod u+x travis_setup.sh
  - source ./travis_setup.sh

install:
  - $CC --version
  - $CXX --version


script:
  - mkdir build
  - cd build
  - cmake ..
  - cmake --build .. --target detector_unit_test
  - sudo ./detector_unit_test
