
language: cpp
os:
 - linux

compiler:
    -clang
    -gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y gcc-4.8; fi


script: make && ./unittest


